# Generated by Django 3.2.7 on 2021-09-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('isbn', models.IntegerField(max_length=10)),
                ('isbn13', models.IntegerField(max_length=13)),
                ('lang', models.CharField(max_length=20)),
                ('num_pages', models.IntegerField(max_length=10)),
                ('ratings_count', models.IntegerField(max_length=10)),
                ('reviews_count', models.IntegerField(max_length=10)),
                ('pub_date', models.DateField()),
                ('publisher', models.CharField(max_length=120)),
            ],
        ),
    ]
